Updated some demos and added a new oom deployment

diff --git a/holmes-meme-generator/failure-more-pods/curl.yaml b/holmes-meme-generator/failure-more-pods/curl.yaml
--- a/holmes-meme-generator/failure-more-pods/curl.yaml
+++ b/holmes-meme-generator/failure-more-pods/curl.yaml
@@ -20,7 +20,7 @@ spec:
           - -c
           - |
             while true; do
-              echo "Checking endpoint http://meme-service:5000...";
-              curl -s http://meme-service:5000 || echo "Failed to reach http://meme-service:5000";
+              echo "Checking endpoint http://meme-gen-service:5000...";
+              curl -s http://meme-gen-service:5000 || echo "Failed to reach http://meme-gen-service:5000";
               sleep 30;
             done;
